sick_scan2: # configuration for sick_scan2_tim_240: For compatibility with ros versions previous to foxy, node and parameter name changed to sick_scan2 for all supported scanner. The type of scanner is configured by scanner_name only.
  ros__parameters:
    hostname : "10.2.99.123"
    frame_id : "lidar_link"
    scanner_name : "sick_tim_5xx"
    port : 2112
    min_ang : -1.396263 #in lidar cordinate frame  see ../doc/3d_coordinate_system_comp.png
    max_ang : +1.396263 #in lidar cordinate frame  see ../doc/3d_coordinate_system_comp.png



lidar_filters:
  ros__parameters:
    filter1:
      name : speckle_filter
      type : laser_filters/LaserScanSpeckleFilter
      params:
        filter_type: 0
        max_range: 2.0
        max_range_difference: 0.05
        filter_window: 2
